"""switched to photo_path storage

Revision ID: 7f73c0750073
Revises: c0d20ac75cfb
Create Date: 2025-11-02 16:56:57.698864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f73c0750073'
down_revision = 'c0d20ac75cfb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        # Step 1: Set all NULL current_state values to False before altering
        batch_op.execute("UPDATE user_details SET current_state = 0 WHERE current_state IS NULL;")

        # Step 2: Alter the column safely
        batch_op.alter_column(
            'current_state',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.text('0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.BLOB(), nullable=True))
        batch_op.alter_column('current_state',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
