"""Initial migration

Revision ID: a71c06dabc2a
Revises: 
Create Date: 2025-11-02 14:04:10.170937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71c06dabc2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.drop_column('photo_mime')
        batch_op.drop_column('photo_data')

    # ### end Alembic commands ###
