"""added active state

Revision ID: c0d20ac75cfb
Revises: fffd5a1477d3
Create Date: 2025-11-02 16:29:30.846785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d20ac75cfb'
down_revision = 'fffd5a1477d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_state', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_column('current_state')

    # ### end Alembic commands ###
