"""Initial migration

Revision ID: e1e526d5103d
Revises: a71c06dabc2a
Create Date: 2025-11-02 14:11:44.037202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e526d5103d'
down_revision = 'a71c06dabc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
