"""Initial migration

Revision ID: fffd5a1477d3
Revises: e1e526d5103d
Create Date: 2025-11-02 14:14:21.295090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fffd5a1477d3'
down_revision = 'e1e526d5103d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_mime', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_details_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_details_phone_number'), ['phone_number'], unique=True)

    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('phone_number'))

    op.drop_table('user_deatails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_deatails',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('photo_data', sa.BLOB(), nullable=True),
    sa.Column('photo_mime', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_deatails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_details_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_details_email'))

    op.drop_table('user_details')
    # ### end Alembic commands ###
